sudo: required
services: 
  - docker

before_install:
  - docker build -t ohmsun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ohmsun/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-583750115313"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_id: "$AWS"
  secret_id: "$SECRET_AWS"  